### ISSUE TITLE
Not compatible with gradle 7.4.1

### ISSUE THREAD

**Issue by lukepighetti** [QuisApp/flutter_contacts#96] opened 2023-02-09 16:38 UTC
flutter_contacts 1.1.5+1 is not compatible with com.android.tools.build:gradle 7.4.1 

```
* What went wrong:
[89](https://github.com/tonalfitness/mobile/actions/runs/4118537358/jobs/7111207194#step:10:90)
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
[90](https://github.com/tonalfitness/mobile/actions/runs/4118537358/jobs/7111207194#step:10:91)
The following dependencies do not satisfy the required version:
[91](https://github.com/tonalfitness/mobile/actions/runs/4118537358/jobs/7111207194#step:10:92)
project ':flutter_contacts' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.0
```

**Comment by joachim-quis** [comment] 2023-02-10 08:20
Duplicate of #69

**Closed by joachim-quis** 2023-02-10 08:20 UTC
