### ISSUE TITLE
Read/write custom ringtones

### ISSUE THREAD

**Issue by AxesandGrinds** [QuisApp/flutter_contacts#112] opened 2023-05-05 21:01 UTC
Thank you for writing the Flutter_contacts plugin (https://pub.dev/packages/flutter_contacts). At the bottom of the plugin page, you mentioned that you are working on "Read/write custom ringtones." I would like to ask about your progress on that task and the timeline for completion. I would be grateful if you can focus on that feature and release it as soon as possible. That functionality is very necessary for an app that my team is working on. Please let me know your thoughts on this.

**Comment by joachim-quis** [comment] 2024-05-27 07:10
Thanks for your interested, @AxesandGrinds - my time is limited at the moment for such feature requests, but I'm always open to reviewing PRs :)

Closing as duplicate of https://github.com/QuisApp/flutter_contacts/issues/22

**Closed by joachim-quis** 2024-05-27 07:10 UTC
