### ISSUE TITLE
Update kotlin 

### ISSUE THREAD

**Issue by mouryaavadhesh** [QuisApp/flutter_contacts#89] opened 2022-12-15 12:13 UTC
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_contacts' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.0

You need to update the latest kotlin version in your code

**Comment by Zelfapp** [comment] 2022-12-17 04:41
Same

![image](https://user-images.githubusercontent.com/11559805/208225436-d18192a3-6fe4-4327-a142-a5e6523c01fc.png)

**Comment by Mohammad-Abureesh** [comment] 2022-12-20 11:53
same issues , withe me when update to latest kotlin version '17.3'

**Comment by codetinker** [comment] 2023-01-20 09:13
> The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher. The following dependencies do not satisfy the required version: project ':flutter_contacts' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.0
> 
> You need to update the latest kotlin version in your code

Same issues

**Comment by DanLux** [comment] 2023-01-27 19:37
I am also facing the same issue right now.

**Comment by joachim-quis** [comment] 2023-02-09 04:31
Thanks for reporting. Will update fix ASAP.

**Comment by joachim-quis** [comment] 2023-02-09 04:32
See also https://github.com/QuisApp/flutter_contacts/issues/90

**Comment by joachimvalente** [comment] 2023-02-10 08:36
Duplicate of #69  (now fixed)

**Closed by joachimvalente** 2023-02-10 08:36 UTC
Labels: bug
