### ISSUE TITLE
App crash issue while updating an existing contact

### ISSUE THREAD

**Issue by hssn-hassnain** [QuisApp/flutter_contacts#108] opened 2023-04-19 08:56 UTC
E:Too many content provider operations between yield points. The maximum number of operations per yield point is 500
I have found out the issue is at FlutterContacts.kt file line 556. This happen when 1 contact have multiple numbers

**Comment by joachim-quis** [comment] 2024-05-27 07:12
Thanks @hssn-hassnain - closing as duplicate of https://github.com/QuisApp/flutter_contacts/issues/140

**Closed by joachim-quis** 2024-05-27 07:12 UTC
