### ISSUE TITLE
Build failed on Android ( flutter_contacts: 1.1.7 )

### ISSUE THREAD

**Issue by minhtuanat4** [QuisApp/flutter_contacts#126] opened 2023-07-19 03:12 UTC
There's an Error in GeneratedPluginRegistrant.java file  which makes the building apk file is failed (ANDROID) 
Version: flutter_contacts: 1.1.7
error: package co.quis.flutter_contacts does not exist
      flutterEngine.getPlugins().add(new co.quis.flutter_contacts.FlutterContactsPlugin());

**Comment by josiahyeow** [comment] 2023-07-20 01:29
I'm getting the following error too when trying to build on the android emulator

```
e: file:///Users/josiahyeow/.pub-cache/hosted/pub.dev/flutter_contacts-1.1.6/android/src/main/kotlin/co/quis/flutter_contacts/FlutterContacts.kt:45:7 Redeclaration: FlutterContacts
e: file:///Users/josiahyeow/.pub-cache/hosted/pub.dev/flutter_contacts-1.1.6/android/src/main/kotlin/co/quis/flutter_contacts/FlutterContactsPlugin.kt:27:7 Redeclaration: FlutterContactsPlugin
e: file:///Users/josiahyeow/.pub-cache/hosted/pub.dev/flutter_contacts-1.1.7/android/src/main/kotlin/co/quis/flutter_contacts/FlutterContacts.kt:45:7 Redeclaration: FlutterContacts
e: file:///Users/josiahyeow/.pub-cache/hosted/pub.dev/flutter_contacts-1.1.7/android/src/main/kotlin/co/quis/flutter_contacts/FlutterContactsPlugin.kt:27:7 Redeclaration: FlutterContactsPlugin
e: file:///Users/josiahyeow/.pub-cache/hosted/pub.dev/flutter_contacts-1.1.7/android/src/main/kotlin/co/quis/flutter_contacts/FlutterContactsPlugin.kt:328:87 Too many arguments for public final fun openExternalPickOrInsert(activity: Activity?, context: Context?, insert: Boolean): Unit defined in co.quis.flutter_contacts.FlutterContacts.Companion

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_contacts:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Exception: Gradle task assembleDebug failed with exit code 1]
```

**Comment by joachim-quis** [comment] 2023-07-29 03:58
Thanks for reporting @minhtuanat4 
Closing as duplicate of #127

**Closed by joachim-quis** 2023-07-29 03:58 UTC
