### ISSUE TITLE
Null in openExternalPick() Response [Android 13]

### ISSUE THREAD

**Issue by ritwizkh** [QuisApp/flutter_contacts#161] opened 2024-05-29 11:53 UTC
I am using the latest version of the `flutter_contacts: ^1.1.8`  to pick the contact from native Android.
The compile apk is working fine on my old device, i.e android 9, but when I am trying the same app on Android 13, it opens the native contacts app, selects the contact, but it's returning Null.
Note: The contact permission is already granted to the app, but still facing issues on Android 13. I didn't test it on iOS.

I am using this in Flutterflow, here is the code which I am using:
```
import 'package:flutter_contacts/flutter_contacts.dart';
Future<ContactPickStruct?> contactPickOpen() async {
final pickedContact = await FlutterContacts.openExternalPick();

    if (pickedContact != null) {
      // Parse contact details inline
      final name = pickedContact.name;
      final personName =
          (name.first.isNotEmpty) ? '${name.first} ${name.last}'.trim() : '';
      final companyName = pickedContact.organizations.isNotEmpty
          ? pickedContact.organizations.first.company
          : '';
      final designation = pickedContact.organizations.isNotEmpty
          ? pickedContact.organizations.first.title
          : '';

      final mobileNumbers =
          pickedContact.phones.map((phone) => phone.number).toList();
      final emails =
          pickedContact.emails.map((email) => email.address).toList();
}
...
}
```

**Comment by ritwizkh** [comment] 2024-06-28 06:42
@joachim-quis - can you please look into this?

**Comment by joachim-quis** [comment] 2024-07-29 21:04
Hi @ritwizkh - is `pickedContact` null or is the result of `contactPickOpen()` null?

**Comment by joachim-quis** [comment] 2024-07-29 21:08
If it's `pickedContact`, could you add some debug print statements in [this function](https://github.com/QuisApp/flutter_contacts/blob/b52126f252e364fc247739e5aa80a1d2060d15a2/android/src/main/kotlin/co/quis/flutter_contacts/FlutterContacts.kt#L674-L720) to see where exactly the function is not working as intended?

**Comment by joachim-quis** [comment] 2024-07-31 23:10
Nevermind - this should now be fixed in [version 1.1.9+1](https://pub.dev/packages/flutter_contacts/versions/1.1.9+1). Please reopen if not.

**Closed by joachim-quis** 2024-07-31 23:10 UTC

**Comment by igopi77** [comment] 2024-08-02 05:28
I have used flutter_contacts: ^1.1.9+1 in my application. I tested opening contacts on Android 14, Android 13, and Android 11, and it worked fine. However, I am unable to open contacts on Android 9.

**Comment by igopi77** [comment] 2024-08-02 05:52
I tested on Android 13, Android 14, and Android 11, and it’s working fine  I suspect the problem may not be related to the Android version.

**Comment by qoiu** [comment] 2024-08-12 06:54
I am using the latest version 1.1.9+2 and have same bug on Android 13. Android 12, emulator is fine. In permission add
<uses-permission android:name="android.permission.READ_CONTACTS"/>
<uses-permission android:name="android.permission.WRITE_CONTACTS"/>
Maybe, I don't use some permission?
There's strange thing: it take only my first contact, but others return null
