### ISSUE TITLE
_contacts!.length =0 , if stored in google account 

### ISSUE THREAD

**Issue by Hararot** [QuisApp/flutter_contacts#23] opened 2021-06-22 20:26 UTC
I appreciate the good work (thanks),

Anyway I used this in my flutter app and it worked fine in the emulator.
I had a contact `ListView.builder` with rows and columns to make a contact list with thumbnails, but when I tried it 
on a real Android 8.0 LG G5 phone the contact list did not work it was blank and no errors or crash massage
it was just empty I tried it on my S9 Android 10.0 it worked fine.

Does this repository work on below Android 10 ? or did I need to edit something somewhere and I missed it.

**Comment by Hararot** [comment] 2021-06-24 20:58
> I appreciate the good work (thanks),
> 
> Anyway I used this in my flutter app and it worked fine in the emulator.
> I had a contact `ListView.builder` with rows and columns to make a contact list with thumbnails, but when I tried it
> on a real Android 8.0 LG G5 phone the contact list did not work it was blank and no errors or crash massage
> it was just empty I tried it on my S9 Android 10.0 it worked fine.
> 
> Does this repository work on below Android 10 ? or did I need to edit something somewhere and I missed it.

**I found out  the problem**, I checked that it works on Android 8.0 by using emulator.
I don't know how to explain this,
but some devices like my LG G5 by default dos not save contacts in storage on phone it stores it **somewhere else that this plugin dos not see**, which in my case was on my google account so when I run `_contacts!.length` it was 0 which explain why the contact list was empty. I did not know how to solve this programmatically :(

but when I moved contacts to be stored in my phone contact list appeared

**Comment by joachim-quis** [comment] 2021-09-05 19:48
Hi @Hararot ! Sorry for the late reply. I'm having trouble understanding where exactly your LG G5 is storing contacts. Is it in the SIM card? If so, is it fine to close this as a duplicate of #26 ?

**Comment by joachim-quis** [comment] 2022-02-22 03:39
Closing, feel free to reopen if needed.

**Closed by joachim-quis** 2022-02-22 03:39 UTC
