### ISSUE TITLE
Trying to update 20 contacts i got this error

### ISSUE THREAD

**Issue by angebagui** [QuisApp/flutter_contacts#1] opened 2021-01-17 14:37 UTC
I/flutter (31118): Iteration >>>> 1
I/flutter (31118): Iteration >>>> 2
I/flutter (31118): Iteration >>>> 3
I/flutter (31118): Iteration >>>> 4
I/flutter (31118): Iteration >>>> 5
I/flutter (31118): Iteration >>>> 6
I/flutter (31118): Iteration >>>> 7
I/flutter (31118): Iteration >>>> 8
I/flutter (31118): Iteration >>>> 9
I/flutter (31118): Iteration >>>> 10
I/flutter (31118): Iteration >>>> 11
I/flutter (31118): Iteration >>>> 12
I/flutter (31118): Iteration >>>> 13
I/flutter (31118): Iteration >>>> 14
I/flutter (31118): Iteration >>>> 15
I/flutter (31118): Iteration >>>> 16
I/flutter (31118): Iteration >>>> 17
I/flutter (31118): Iteration >>>> 18
I/flutter (31118): Iteration >>>> 19
E/AndroidRuntime(31118): FATAL EXCEPTION: DefaultDispatcher-worker-12
E/AndroidRuntime(31118): Process: ci.dixapp, PID: 31118
E/AndroidRuntime(31118): android.content.OperationApplicationException: Too many content provider operations between yield points. The maximum number of operations per yield point is 500
E/AndroidRuntime(31118): 	at android.database.DatabaseUtils.readExceptionWithOperationApplicationExceptionFromParcel(DatabaseUtils.java:161)
E/AndroidRuntime(31118): 	at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:528)
E/AndroidRuntime(31118): 	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:532)
E/AndroidRuntime(31118): 	at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:520)
E/AndroidRuntime(31118): 	at android.content.ContentResolver.applyBatch(ContentResolver.java:1875)
E/AndroidRuntime(31118): 	at co.quis.flutter_contacts.FlutterContacts$Companion.update(FlutterContacts.kt:469)
E/AndroidRuntime(31118): 	at co.quis.flutter_contacts.FlutterContactsPlugin$onMethodCall$3.invokeSuspend(FlutterContactsPlugin.kt:92)
E/AndroidRuntime(31118): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(31118): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(31118): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
E/AndroidRuntime(31118): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
E/AndroidRuntime(31118): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
E/AndroidRuntime(31118): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by joachimvalente** [comment] 2021-01-17 20:09
Hi @angebagui thanks for reporting this! Could you post your code? With the logs alone it's hard to tell what's wrong.

**Comment by angebagui** [comment] 2021-01-18 13:55
for(Contact contact in contacts){
        
        Contact newContact = await convertPhone(contact);
       
        ++contactCount;

        print('Iteration >>>> $contactCount');
        
      }

**Comment by angebagui** [comment] 2021-01-18 14:04
the function convertPhone ()
  static Future<Contact> convertPhone(Contact contact) async {

    final List<Phone> phones = contact.phones == null ? [] : contact.phones.toList();
    final List<Phone> newPhones = [];


    for(Phone phone in phones){

      bool isValid = isValidPhone(phone);

      if(!isValid){

        newPhones.add(phone);
        continue;
      }

      if(IvoryCostPhoneUtil.isConverted(phone)){
        newPhones.add(phone);
        continue;
      }

      // When it is valid phone
      String simpleNumber = IvoryCostPhoneUtil.simpleNumber(phone.number);
      // RegionInfo regionInfo = await PhoneNumberUtil.getRegionInfo(phoneNumber: phone.normalizedNumber, isoCode: COUNTRY_ISO);

      String operator = IvoryCostPhoneUtil.operatorByPhoneNumber(simpleNumber);

      bool isMobile = IvoryCostPhoneUtil.isMobile(simpleNumber);
      bool isFixedLine = IvoryCostPhoneUtil.isFixedLine(simpleNumber);

      operator = operator.toLowerCase();

      if(IvoryCostPhoneUtil.operators.contains(operator)){
        String phoneNumber = simpleNumber;

        String operatorPrefix = "";

        if(isMobile){

          operatorPrefix = IvoryCostPhoneUtil.mobileOperators[operator];

        }

        if(isFixedLine){
          operatorPrefix = IvoryCostPhoneUtil.fixedLineOperators[operator];
        }

      
        if(operatorPrefix != null){
          String newPhoneNumber = "+225 "+operatorPrefix+" "+phoneNumber;
          newPhoneNumber  = IvoryCostPhoneUtil.normalizePhoneNumber(newPhoneNumber);

         /* Phone newPhone = new Phone(newPhoneNumber,
              normalizedNumber: newPhoneNumber,
              customLabel: "PNN"
          );*/

          Phone newPhone = new Phone(newPhoneNumber,
              normalizedNumber: "",
              customLabel: "PNN"
          );

          newPhones.add(newPhone);
          if(!newPhones.contains(phone)){
            newPhones.add(phone);
          }

        }



      }

    }

    contact.phones = newPhones;



    await FlutterContacts.updateContact(contact);


    //print("Converted");

    return contact;


  }

**Comment by joachimvalente** [comment] 2021-02-15 01:22
Can't reproduce, closing.

A few ideas to try in such cases:
* are you trying to update a contact with more than 500 properties? (see [SO question](https://stackoverflow.com/questions/15525440/bulk-update-of-more-than-500-contacts))
* did you forget `await` when calling `FlutterContacts.update()`?
* if it fails for the 19th contact, can you retry the same code with just that one contact, and does it still fail?
* can you try adding `android.util.Log.w("XXX", "${ops.size}")` before [this line](https://github.com/QuisApp/flutter_contacts/blob/4f86f5ed25ee97aff5688fee1b653bb566366e3a/android/src/main/kotlin/co/quis/flutter_contacts/FlutterContacts.kt#L469)
* etc

**Closed by joachimvalente** 2021-02-15 01:22 UTC
