### ISSUE TITLE
Flutter contact on build appbundle

### ISSUE THREAD

**Issue by Mohammad-Abureesh** [QuisApp/flutter_contacts#90] opened 2022-12-20 09:24 UTC
current kotlin version 1.4.0 replace to  **ext.kotlin_version = '1.7.10'**

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher. 

The following dependencies do not satisfy the required version: project ':flutter_contacts' -> org.jetbrains.kotlin:kotlin-gradle-plugin**:1.4.0**

**Comment by joachim-quis** [comment] 2023-02-09 04:31
Duplicate of #89

**Closed by joachim-quis** 2023-02-09 04:31 UTC
